import Head from "next/head";
import {Link} from "next/link";
import react, {useState} from 'react';
import { PortableText } from "@portabletext/react";
import { sanityClient, urlFor } from "../lib/sanity";

const queryString = `*[_type=="self" && slug.current == "pius-fredrick"][0]{
  slug,
  officeName->{officeName, officeWhatsapp, officeTwitter, officeInstagram},
  userName->{_id,fname, userWhatsapp, userTwitter, userInstagram,profile}
}`;

export default function Home({ userData }) {
  const {slug, userName } = userData;
  const [show, setShow] = useState(false);
  const [officeShow, setOfficeShow] = useState(false);
  return (
    <div>
      <Head>
        <title>nfc-project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="main-app">
          <div className="app-container d-flex-col">
            <div className="top d-flex-col center-align w-80">
              <div className="img-holder">
                <img src="./assets/img/pius.jpg" alt="x" />
              </div>
              <div className="client-intro d-flex-col center-align">
                <h2>{slug.current}</h2>
                
                <div className="office-intro d-flex-row">
                  <p className="office">Dremor_graphics TZ</p>
                  <span className="dot-sm"></span>
                  <p className="profession">Graphics designer</p>
                </div>
                <button className="button call d-flex-row">
                  <a href="#" className="d-flex-row">
                  <i class="bi bi-telephone-fill"></i>
                    <p> 0755 363 220</p>
                  </a>
                </button>
              </div>
            </div>
            <div className="middle d-flex-col w-80 center-align">
              <div className="header self d-flex-row center-align" onClick={e=>setShow(!show)}>
                <img src="./assets/icons/person.png" alt="" className="icon" />
                <p>self info</p>
              </div>
              <div className={show? "active account-holder d-flex-col w-96" : "account-holder d-flex-col w-96"}>
                <button className="button social-btn d-flex-row">
                  <a
                    href="https://twitter.com/PiusFredrick6?t=Er1LDOLqJLgiwjHUYLOEMg&s=01"
                    className="d-flex-row"
                  >
                    <img src="./assets/icons/twitter.ico" alt="" className="icon" />
                    <p>twitter</p>
                  </a>
                </button>
                <button className="button social-btn d-flex-row">
                  <a
                    href="https://instagram.com/dres_pick1417?igshid=OGQ2MjdiOTE="
                    className="d-flex-row"
                  >
                    <img
                      src="./assets/icons/instagram.ico"
                      alt=""
                      className="icon"
                    />
                    <p>instagram</p>
                  </a>
                </button>
                <button className="button social-btn d-flex-row">
                  <a href="https://whatsapp.me/<0755363220>" className="d-flex-row">
                    <img
                      src="./assets/icons/whatsapp.ico"
                      alt=""
                      className="icon"
                    />
                    <p>Whatsapp</p>
                  </a>
                </button>
              </div>
            </div>
            <div className="bottom w-80 center-align d-flex-col">
              <div className="header d-flex-row" onClick={e=>setOfficeShow(!officeShow)}>
                <img src="./assets/icons/office.png" alt="" className="icon" />
                <p>Office info</p>
              </div>

              <div className={officeShow? "active account-holder d-flex-col w-96" : "account-holder d-flex-col w-96"}>
                <button className="button social-btn d-flex-row">
                  <a href="https://twitter.com/pius_fredick" className="d-flex-row">
                    <img src="./assets/icons/twitter.ico" alt="" className="icon" />
                    <p>twitter</p>
                  </a>
                </button>
                <button className="button social-btn d-flex-row">
                  <a href="https://twitter.com/pius_fredick" className="d-flex-row">
                    <img
                      src="./assets/icons/instagram.ico"
                      alt=""
                      className="icon"
                    />
                    <p>instagram</p>
                  </a>
                </button>
                <button className="button social-btn d-flex-row">
                  <a href="https://twitter.com/pius_fredick" className="d-flex-row">
                    <img
                      src="./assets/icons/whatsapp.ico"
                      alt=""
                      className="icon"
                    />
                    <p>Whatsapp</p>
                  </a>
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps(){
  const userData = await sanityClient.fetch(queryString);
  console.log(userData);
  return {
    props: {userData}
  };
}
